#!/bin/zsh
#
###? git-merge-request - push and open webpage to create merge request
###?
###? usage: git-merge-request
#
## function git-merge-request {
    
    declare -A targets=( [new-tencent]=release-cn-tencent [new-icebird]=release-cn-icebird [new-korea]=release-korea [new-vn]=release-vn [new-hant]=release-hant [new-japan]=release-japan [new-tailand]=release-tailand)
    declare -A names=( [new-tencent]=腾讯 [new-icebird]=买量 [new-korea]=韩国 [new-vn]=越南 [new-hant]=繁体 [new-japan]=日本 [new-tailand]=泰国)
    
    local branch_name=$(git rev-parse --abbrev-ref HEAD)
    local target=${targets[${branch_name}]}

    git push
    
    if [ -n "${target+1}" ];
    then
        local base="$(git remote get-url --push origin | sed -e 's|:|/|' -e 's|git@|https://|' -e 's/.git$//')"
        local title="${names[${branch_name}]}版本$(date -u +%Y%m%d)内容"
    
        open "${base}/-/merge_requests/new?merge_request[source_branch]=${branch_name}&merge_request[target_branch]=${target}&merge_request[squash]=false&merge_request[title]=${title}"

    else 
        open "https://git.youle.game/tkw/server/tkw_server/-/merge_requests/new?merge_request%5Bsource_branch%5D=${branch_name}"
    fi
# }
